#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Apr 29 18:42:10 EDT 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0ebda2b1aa344fb0a285af38b353be2c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ds_top_wrapper_tb_behav xil_defaultlib.ds_top_wrapper_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 0ebda2b1aa344fb0a285af38b353be2c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ds_top_wrapper_tb_behav xil_defaultlib.ds_top_wrapper_tb xil_defaultlib.glbl -log elaborate.log

